name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Assicurati di utilizzare la versione di Node.js compatibile

    - name: Install dependencies
      run: npm install

    #- name: Build the app
    #  run: npm run build

    - name: Package the app
      run: npm run make

    - name: List files in out directory 
      if: matrix.os == 'windows-latest' 
      run: dir out\ 
      
    - name: List files in out directory 
      if: matrix.os != 'windows-latest' 
      run: ls -la out/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: out/

    - name: Extract tag name 
      id: extract_tag 
      uses: actions/github-script@v6 
      with: 
        script: | 
          const ref = process.env.GITHUB_REF; 
          const tagName = ref.replace('refs/tags/', ''); 
          core.setOutput('TAG_NAME', tagName);

    - name: Rename artifacts with tag name 
      if: matrix.os == 'windows-latest' 
      run: | 
        rename out\make\zip\win32\x64\*.zip out\mtc-repertoire-engine-${{ matrix.os }}-${{ steps.extract_tag.outputs.TAG_NAME }}.zip 
        rename out\make\squirrel.windows\x64\*.nupkg out\mtc-repertoire-engine-${{ matrix.os }}-${{ steps.extract_tag.outputs.TAG_NAME }}.nupkg 
        rename out\make\squirrel.windows\x64\*-setup.exe out\mtc-repertoire-engine-setup-${{ matrix.os }}-${{ steps.extract_tag.outputs.TAG_NAME }}.exe 
        
    
    - name: List files in out directory 
      if: matrix.os == 'windows-latest' 
      run: dir out\ 

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ steps.extract_tag.outputs.TAG_NAME }}
        release_name: Release ${{ steps.extract_tag.outputs.TAG_NAME }}
        draft: true
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: out/mtc-repertoire-engine-${{ matrix.os }}-${{ steps.extract_tag.outputs.TAG_NAME }}.zip
        asset_name: mtc-repertoire-engine-${{ matrix.os }}-${{ steps.extract_tag.outputs.TAG_NAME }}.zip
        asset_content_type: application/zip
